import React, { useEffect, useState } from 'react';
import { useAuth } from '../../context/AuthContext';
import api from '../../services/api';
import {
  BookOpen,
  AlertTriangle,
  Lightbulb,
  CheckCircle2,
  TrendingUp,
  ArrowRight,
  Handshake,
  Download,
} from 'lucide-react';
import {
  ResponsiveContainer,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  Legend,
} from 'recharts';

const CurriculumGapAnalysis = () => {
  const { profile } = useAuth();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchAnalytics = async () => {
      if (!profile?._id) return;
      try {
        setLoading(true);
        const res = await api.get(`/analytics/college/${profile._id}`);
        if (res.data.success) {
          setData(res.data.data);
        }
      } catch (err) {
        console.error('Failed to load curriculum analytics', err);
      } finally {
        setLoading(false);
      }
    };
    fetchAnalytics();
  }, [profile?._id]);

  if (loading) {
    return (
      <div className="p-16 text-center text-xs text-slate-400 animate-pulse">
        Comparing university student skill distribution with corporate recruitment requirements...
      </div>
    );
  }

  const {
    collegeName = 'Engineering Institution',
    totalStudents = 0,
    placementRate = 0,
    comparison = [],
    curriculumRecommendations = [],
  } = data || {};

  return (
    <div className="space-y-6 max-w-6xl mx-auto">
      {/* Header */}
      <div className="bg-gradient-to-r from-slate-900 via-amber-950 to-slate-900 rounded-3xl p-6 sm:p-8 text-white shadow-xl flex flex-col md:flex-row md:items-center md:justify-between gap-6">
        <div>
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold bg-amber-500/20 text-amber-300 border border-amber-400/30 mb-2">
            <AlertTriangle className="w-3.5 h-3.5" />
            Curriculum Intervention Radar
          </div>
          <h1 className="text-2xl sm:text-3xl font-black tracking-tight">
            Institutional Skill Gap & Training Roadmap
          </h1>
          <p className="text-xs sm:text-sm text-slate-300 mt-1 max-w-xl">
            Directly identifying <b>High Industry Demand + Low Student Availability</b> to recommend curriculum updates, workshops, and faculty enablement.
          </p>
        </div>

        <div className="text-right shrink-0">
          <div className="text-3xl font-black text-amber-400">
            {curriculumRecommendations.length}
          </div>
          <div className="text-[11px] font-bold text-slate-300 uppercase tracking-wider">
            Interventions Needed
          </div>
        </div>
      </div>

      {/* RECOMMENDED INTERVENTIONS LIST (DIRECT PROBLEM STATEMENT REQUIREMENT) */}
      <div className="bg-white rounded-3xl border border-slate-200 p-6 sm:p-8 shadow-sm">
        <div className="flex items-center justify-between pb-4 border-b border-slate-100 mb-6">
          <div>
            <h2 className="text-base font-bold text-slate-900 flex items-center gap-2">
              <Lightbulb className="w-5 h-5 text-amber-500 fill-amber-500" />
              Prescribed Academia–Industry Action Items
            </h2>
            <p className="text-xs text-slate-500">
              Generated by comparing 20+ corporate openings against your verified student skill repository
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {curriculumRecommendations.map((item, idx) => (
            <div
              key={idx}
              className="p-5 rounded-2xl border border-amber-200 bg-amber-50/30 flex flex-col justify-between"
            >
              <div>
                <div className="flex items-center justify-between gap-2 mb-2">
                  <span className="text-sm font-black text-slate-900">{item.skill}</span>
                  <span
                    className={`text-[10px] font-extrabold uppercase px-2 py-0.5 rounded ${
                      item.impact === 'Critical'
                        ? 'bg-rose-100 text-rose-800 border border-rose-200'
                        : 'bg-amber-100 text-amber-800 border border-amber-200'
                    }`}
                  >
                    {item.impact} Priority
                  </span>
                </div>

                <div className="flex items-center gap-4 text-xs font-semibold text-slate-600 mb-3">
                  <div>
                    Industry Demand: <b className="text-brand-600">{item.demandPct}%</b>
                  </div>
                  <div>•</div>
                  <div>
                    Student Readiness: <b className="text-slate-800">{item.studentPct}%</b>
                  </div>
                </div>

                <p className="text-xs text-slate-700 bg-white p-3 rounded-xl border border-amber-100/80 leading-relaxed font-medium">
                  "{item.recommendation}"
                </p>
              </div>

              <div className="mt-4 pt-3 border-t border-amber-200/50 flex items-center justify-between text-xs">
                <span className="text-[11px] font-bold text-slate-500">
                  Target: Eliminate {item.gap}% Gap
                </span>
                <span className="text-[11px] font-extrabold text-amber-700 flex items-center gap-1">
                  <Handshake className="w-3.5 h-3.5" /> Launch Industry MoU
                </span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* COMPARATIVE DEMAND VS STUDENT READINESS CHART */}
      <div className="bg-white rounded-3xl border border-slate-200 p-6 sm:p-8 shadow-sm">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h3 className="text-base font-bold text-slate-900 flex items-center gap-2">
              <TrendingUp className="w-5 h-5 text-brand-600" />
              Corporate Demand (%) vs. Student Skill Availability (%)
            </h3>
            <p className="text-xs text-slate-500">
              Real-time delta highlights where training programs will produce maximum placement lift
            </p>
          </div>
        </div>

        <div className="w-full h-80">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={comparison} margin={{ top: 10, right: 10, left: -20, bottom: 20 }}>
              <XAxis dataKey="skill" tick={{ fontSize: 11, fill: '#475569' }} />
              <YAxis unit="%" tick={{ fontSize: 11, fill: '#475569' }} />
              <Tooltip formatter={(val) => [`${val}%`, '']} />
              <Legend verticalAlign="top" wrapperStyle={{ paddingBottom: 15 }} />
              <Bar dataKey="demand" fill="#2563eb" radius={[4, 4, 0, 0]} name="Industry Demand %" />
              <Bar dataKey="students" fill="#10b981" radius={[4, 4, 0, 0]} name="Student Availability %" />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>
    </div>
  );
};

export default CurriculumGapAnalysis;
